### ISSUE TITLE
Isolate/Unisolate Endpoint - Endpoint not found

### ISSUE THREAD

**Issue by lawiet47** [ebarti/cortex-xdr-client#30]
During the invocation of the `endpoints_api.isolate_endpoints` or `endpoints.api.unisolate_endpoints` the client returns `b'{"reply": {"err_code": 500, "err_msg": "An error occurred while processing XDR public API - No endpoint was found for creating the requested action", "err_extra": "can\'t create group action id for ISOLATE"}}'` even though provided endpoint_list is selected directly from the Cortex XDR dashboard``

**_Python 3.9
API Version 1.7.2_**

**Comment by lawiet47** [comment]
Same thing value submitting the request for just one endpoint with `{'request_data': {'endpoint_id': 'EXISTING_ENDPOINT_ID'}}`

**Comment by ebarti** [comment]
Hey @lawiet47 are you sure of this? Makew sure you are isolating with the ID, not the Endpoint Name (as their API docs **WRONGLY** suggest)

**Comment by lawiet47** [comment]
It's the endpoint_id in the md5 hash format, obtained from the cortex dashboard

**Comment by ebarti** [comment]
I cannot reproduce the issue

**Comment by lawiet47** [comment]
Can you please share the command that you execute? I'm still getting the same error

**Comment by lawiet47** [comment]
I'm gonna go ahead and close this issue as this is expected for the endpoint to have the opposite state when performing either the `isolate` or `unisolate`.
