### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by omer-an** [ebarti/cortex-xdr-client#47]
hi from the cortex i have already the hash authentication so another hash will get authentication issue :
```
Traceback (most recent call last):
  ...
  File "ib/python3.9/site-packages/cortex_xdr_client/api/xql_api.py", line 51, in start_xql_query
    response = self._call(call_name="start_xql_query", json_value=request_data)
  File "lib/python3.9/site-packages/cortex_xdr_client/api/base_api.py", line 46, in _call
    return self._execute_call(url=url,
  File "python3.9/site-packages/cortex_xdr_client/api/base_api.py", line 67, in _execute_call
    response.raise_for_status()
  File "python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url
```
is there a way to add flag to set hash api key that will put instead of "Authorization": api_key_hash "Authorization": self._api_key
in _get_headers() line 30 in base_api.py file? or how can i get the not hash api from the product ?

**Comment by omer-an** [comment]
query still not ended but api crash :

```
Traceback (most recent call last):
...
  File "/cortex_xdr_client/api/xql_api.py", line 75, in get_query_results
    raise InvalidResponseException(response, ["number_of_results"])
cortex_xdr_client.api.models.exceptions.InvalidResponseException: Invalid response from server. 
 Got: {'reply': {'status': 'PENDING'}}. Missing items: ['number_of_results']
```
this response is expected when api take some time to get answer but the api does not wait and throw exception

**Comment by ebarti** [comment]
Hey @omer-an Sorry for the late reply here. Thank you for creating this issue, as I am an advanced auth user I did not implement standard auth. I pushed a PR to enable it

**Comment by omer-an** [comment]
thank you so much, will it be possible to push this pr to the version in pypi?

**Comment by ebarti** [comment]
Yes indeed, I just pushed 1.8.0 out. I am reopening this as it got closed automatially - but I still need to dig into the errors you faced on querying.

**Comment by ebarti** [comment]
@omer-an Is this still an issue?
